### ISSUE TITLE
Jnxplus not compatible with nx 17

### ISSUE THREAD

**Issue by shanon84** [khalilou88/jnxplus#1206]
Hey,
I have tried to use jnxplus with the newest nx 17 version and it is failing (nx-maven).
graph-utils uses workspaceDataDirectory from nx cache-directory. This only exist in nx 19.
It would be nice to either dont use it or increase the minimal nx version listed in nx-maven readme to 19.

**Comment by khalilou88** [comment]
My idea is one version of nx should be compatible with a version of nx.
jnxplus 1.x.x is compatible with nx 19: https://github.com/khalilou88/jnxplus/issues/875

So jnxplus 2.x.x will be compatible for nx 20.


If you want to use nx 17, i can remove use of `workspaceDataDirectory`  in a specific version 0.x.x but maybe the graph has changes since version nx 17

**Comment by shanon84** [comment]
it is fine. I asumed it is 17 compatible, because of the readme:
https://github.com/khalilou88/jnxplus/tree/main/packages/nx-maven
Only 17 is mentioned. Maybe update the readme to prevent confusion.

**Comment by shanon84** [comment]
@khalilou88 yes, we are stil using nx 17. The 0.50.1 seems to work like a charm. Thank you.
