### ISSUE TITLE
[feature] "dependencies" property

### ISSUE THREAD

**Issue by draylegend** [khalilou88/jnxplus#28]
Add `dependencies` property for `application` and `library` as in [spring starter](https://start.spring.io).

Maybe as a list with autocompletion based on [starter dependencies](https://start.spring.io/dependencies)

**Comment by khalilou88** [comment]
Thanks @vladimirdrayling 
I have in my mind some ideas like this but instead of providing dependencies, the user can generate some kind of lib like database lib: in this case we will ask for database name (mysql, postgres...) and so on.
Something like https://github.com/jhipster/jhipster-lite

But for now, I really want to make the plugin stable and consistent with Nx world.
