### ISSUE TITLE
Maven and multi-module projects with libraries

### ISSUE THREAD

**Issue by MikeEnRegalia** [khalilou88/jnxplus#60]
I'm trying to set up an nx project with two maven apps and a maven library. How is that supposed to work with nx-boot-maven? It sets up the maven poms correctly, but in order to build an app I need to run maven from the parent pom folder. If I run it from the app folder, maven cannot find the libary dependency. Since nx-boot-maven also seems to run mvn from the app folder, it also fails.

Am I doing something wrong here? How is it supposed to work?

EDIT: I think I found the actual problem, and in that case there would be a simple fix: https://github.com/khalilou88/jnxplus/pull/61

**Comment by khalilou88** [comment]
Hi @MikeEnRegalia thank you for using this plugin. What are you asking is something provided by NX. This is why we don't use maven for this kind of features. 
Maybe is a new bug and I need to know the version that you have used with the commands. Unfortunately I can't test this option with e2e tests because the dep-graph is not working well for plugins.
The `-am` option well be dangerous because it will build the libs and will not use the NX cache.

**Comment by khalilou88** [comment]
I just did this tutorial https://dev.to/gridou/announcing-jnxplus-nx-boot-maven-4g28 with Nx version 14.3.6 and @jnxplus/nx-boot-maven version 2.2.1 and I didn't face that problem you mention in the issue.

**Comment by khalilou88** [comment]
I found this on NX repo : https://github.com/nrwl/nx/discussions/9725

**Comment by khalilou88** [comment]
@MikeEnRegalia just published the version 2.3.0 with the fix I suggest.
Please test it and give me a feedback.
