### ISSUE TITLE
nx generate:library with -directory flag adding directory name with backslash

### ISSUE THREAD

**Issue by nosaku** [khalilou88/jnxplus#77]
nx generate:library with -directory flag adding directory name with backslah

Example
nx generate @jnxplus/nx-boot-maven:library testing --directory=shared\java\api-access

adds the package name as:
package com.example.shared\java\api-access.testing;

ideally it should be (removing the dash)
package com.example.shared.java.api.access.testing;

**Comment by khalilou88** [comment]
Until now I was not expecting that case. I create a test and the project will not compile with dash. See here https://github.com/khalilou88/jnxplus/actions/runs/2860222226

I need to think more about the solution. use "/" instead of "-" like you suggest. Or remove the "-" (api-access will become apiaccess).

Also I need to add the underscore case

**Comment by nosaku** [comment]
Hi @khalilou88 thank you for acknowledging the issue. Yeah right it will not compile and  I need to manually change the package declarations etc. Regarding the naming convention, underscore is not to be used as per Google conventions hence mentioned as a "dot'. Or apiaccess also makes sense without a dot.

**Comment by khalilou88** [comment]
@nosaku thanks for your reply. I really prefer the second option (just removing the "-").
And in the future version you can have an option to use a short package name without the directory.
https://github.com/khalilou88/jnxplus/pull/71

**Comment by khalilou88** [comment]
@nosaku the version 3.1.0 contains a fix to remove dash from packageName.
